console.log("Basic19 Math Object InJavaScrip ALU Operations");
let a = 10;
let b = 20;
let c = a + b;
c = a - b;
c = a * b;
c = a / b;
c = a % b;
console.log("Addition of a and b is: " + c);
// Explore the Math Object in JavaScript
console.log("Explore the Math Object in JavaScript");
c = Math;
console.log(c);
let z = Math.sqrt(144);
console.log("Square root of 144 is: " + z);
z = Math.pow(2, 3);
console.log("2 to the power of 3 is: " + z);
z = Math.ceil(2.2);
console.log("Ceiling of 2.2 is: " + z);
z = Math.floor(2.2);
console.log("Floor of 2.2 is: " + z);
z = Math.PI;
console.log("PI is: " + z);
z = Math.E;
console.log("E is: " + z);
z = Math.abs(-2.2);
console.log("Absolute value of -2.2 is: " + z);
z = 100000 * Math.random();
console.log("Random value is: " + z);  
